version: '3'

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
      - ./userDataDir:/usr/src/wpp-server/userDataDir
    ports:
      - '21465:21465'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: wpp-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: wpp-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  wppconnect_tokens: {}
  mongo_data: {}
  redis_data: {}
